### ISSUE TITLE
I am trying to get it to work for XP-Pen

### ISSUE THREAD

**Issue by rajhlinux** [sakhmatd/huion-freebsd#1]
Hello,

I replaced many of the huion variables with XP-Pen info.

Does not work for me on FreeBSD 13.1

Any ideas?

I am using XP-Pen Star G640 drawing pad.

Thanks.

**Comment by sakhmatd** [comment]
Hi!

XP-Pen is not a huion device, so I am not surprised.

However, a similar approach might work, if your tablet also presents itself as a /dev/ums device.

Do you get a /dev/ums device for your tablet and did you replace the vendor info in the quirks added by the service?

**Comment by sakhmatd** [comment]
Since there was no reply on this issue, I am going to close it.
