### ISSUE TITLE
This works on the H950P

### ISSUE THREAD

**Issue by Amooti73** [sakhmatd/huion-freebsd#2]
That's all!  I just wanted to let you know, but didn't know how else to communicate the information!  I followed your directions and they simply worked!  Thanks!

I'm not sure how I or others missed this repository.  I had posted about HUION on the freebsd forum in June of last year when this repository already existed.  Here is that [post](https://forums.freebsd.org/threads/can-the-xf86-input-usbtablet-driver-be-ported-to-freebsd.85376/).  Unfortunately, this repository never turned up in my searches at that time.

I am using ghostbsd which is based on FreeBSD 13.2-STABLE and using a Lenove ThinkPad E14 G2.

**Comment by sakhmatd** [comment]
Hi! 

Thanks for letting me know, I'll edit the readme accordingly.
I don't have other HUION tablets to test this on.

Maybe it's worthwhile making a forum post about this so other people can find it.
